# Generated by Django 4.2.6 on 2023-10-23 09:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('first_contact', models.DateField(default='')),
                ('origin_city', models.CharField(max_length=50)),
                ('origin_street', models.CharField(max_length=50)),
                ('origin_post_code', models.CharField(max_length=50)),
            ],
        ),
    ]
