# Generated by Django 4.2.6 on 2023-10-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('shortage', models.CharField(default='', max_length=5)),
                ('processing_time', models.DurationField(default='')),
                ('date_start', models.DateField(default=None, null=True)),
                ('date_end', models.DateField(default=None, null=True)),
                ('features', models.CharField(default='', max_length=500)),
                ('client', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('project_lead', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_projects', to='employees.employee')),
                ('project_team', models.ManyToManyField(default='', related_name='team_projects', to='employees.employee')),
            ],
        ),
    ]
