# Generated by Django 4.2.6 on 2023-11-07 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_current_project'),
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contractor',
            field=models.ForeignKey(default='', limit_choices_to={'profession': 'lead'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor', to='employees.employee'),
        ),
    ]
