# Generated by Django 4.2.6 on 2023-10-23 09:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('origin_city', models.CharField(max_length=50)),
                ('origin_street', models.CharField(max_length=50)),
                ('origin_post_code', models.CharField(max_length=50)),
                ('profession', models.CharField(choices=[('lead', 'Geschäftsführung'), ('architect', 'Architekt'), ('ingenieur', 'Bauingenieur'), ('technician', 'Bautechniker'), ('backoffice', 'backoffice'), ('freelancer', 'Freiberufliche'), ('other', 'Andere')], default='', max_length=50)),
                ('entry_date', models.DateField(default=None, null=True)),
                ('leaving_date', models.DateField(default=None, null=True)),
                ('working_hours', models.IntegerField(default='')),
                ('salary', models.IntegerField(default='')),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
    ]
