# Generated by Django 4.2.6 on 2023-11-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('employees', '0003_alter_employee_current_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='current_project',
            field=models.ManyToManyField(blank=True, default='', to='project.project'),
        ),
    ]
