# Generated by Django 4.2.6 on 2023-10-23 09:36

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('company', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
            ],
        ),
    ]
